### PR TITLE
Update spring dependencies

### PR DESCRIPTION
**Pull request by xurror**

### CODE REVIEW

**Review by aasaru — APPROVED** [review]

**Comment by aasaru** [comment]
@xurror sorry about delay in my response.
When you create a pull request, could you mention me or assign me the review, this way I should get a email notification. Thanks!

**Comment by xurror** [comment]
Will do from now on.
There are some libraries which do not have branch spring_boot_2.hope you
create them soon

**Comment by aasaru** [comment]
Sorry, I thought I had created branches to all of the repositories.

I now created all the missing branches (repos listed below).
Please note that I didn't change the version numbers inside them (as I didn't have time). Would you be able to add them yourself together with the PR?

https://github.com/apache/fineract-cn-demo-server/tree/spring_boot_2
https://github.com/apache/fineract-cn-service-starter/tree/spring_boot-2
https://github.com/apache/fineract-cn-template/tree/spring_boot_2
https://github.com/apache/fineract-cn-provisioner/tree/spring_boot_2
https://github.com/apache/fineract-cn-rhythm/tree/spring_boot_2
https://github.com/apache/fineract-cn-accounting/tree/spring_boot_2
https://github.com/apache/fineract-cn-office/tree/spring_boot_2
https://github.com/apache/fineract-cn-customer/tree/spring_boot_2
https://github.com/apache/fineract-cn-group/tree/spring_boot_2
https://github.com/apache/fineract-cn-deposit-account-management/tree/spring_boot_2
https://github.com/apache/fineract-cn-portfolio/tree/spring_boot_2
https://github.com/apache/fineract-cn-teller/tree/spring_boot_2
https://github.com/apache/fineract-cn-reporting/tree/spring_boot_2
https://github.com/apache/fineract-cn-notifications/tree/spring_boot_2
https://github.com/apache/fineract-cn-cheques/tree/spring_boot_2

**Comment by xurror** [comment]
Sure. Not a problem

**Comment by xurror** [comment]
Please, also create branches for
https://github.com/apache/fineract-cn-permitted-feign-client and
https://github.com/apache/fineract-cn-data-jpa

**Comment by aasaru** [comment]
Done:
https://github.com/apache/fineract-cn-permitted-feign-client/tree/spring_boot_2
https://github.com/apache/fineract-cn-data-jpa/tree/spring_boot_2

**Comment by xurror** [comment]
Thanks

**Pull request merged**
